# Add some style to Padrino. Plugin to install ZURB Foundation on Padrino
#
# Created by Felipe Cabargas <felipe@cabargas.com>
# Copyleft please!
#
# SCSS
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation.scss", "app/stylesheets/foundation.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/normalize.scss", "app/stylesheets/normalize.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/_functions.scss", "app/stylesheets/foundation/_functions.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/_settings.scss", "app/stylesheets/foundation/_settings.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_accordion.scss", "app/stylesheets/foundation/components/_accordion.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_alert-boxes.scss", "app/stylesheets/foundation/components/_alert-boxes.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_block-grid.sc", "app/stylesheets/foundation/components/_block-grid.sc"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_breadcrumbs.sc", "app/stylesheets/foundation/components/_breadcrumbs.sc"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_button-groups.scss", "app/stylesheets/foundation/components/_button-groups.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_buttons.scss", "app/stylesheets/foundation/components/_clearing.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_clearing.scss", "app/stylesheets/foundation/components/_buttons.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_dropdown-buttons.scss", "app/stylesheets/foundation/components/_dropdown-buttons.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_dropdown.scss", "app/stylesheets/foundation/components/_dropdown.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_flex-video.scss", "app/stylesheets/foundation/components/_flex-video.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_forms.scss", "app/stylesheets/foundation/components/_forms.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_global.scss", "app/stylesheets/foundation/components/_global.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_grid.scss", "app/stylesheets/foundation/components/_grid.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_inline-lists.scss", "app/stylesheets/foundation/components/_inline-lists.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_joyride.scss", "app/stylesheets/foundation/components/_joyride.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_keystrokes.scss", "app/stylesheets/foundation/components/_keystrokes.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_labels.scss", "app/stylesheets/foundation/components/_labels.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_magellan.scss", "app/stylesheets/foundation/components/_magellan.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_offcanvas.scss", "app/stylesheets/foundation/components/_offcanvas.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_orbit.scss", "app/stylesheets/foundation/components/_orbit.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_pagination.scss", "app/stylesheets/foundation/components/_pagination.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_panels.scss", "app/stylesheets/foundation/components/_panels.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_pricing-tables.scss", "app/stylesheets/foundation/components/_pricing-tables.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_progress-bars.scss", "app/stylesheets/foundation/components/_progress-bars.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_range-slider.scss", "app/stylesheets/foundation/components/_range-slider.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_reveal.scss", "app/stylesheets/foundation/components/_reveal.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_side-nav.scss", "app/stylesheets/foundation/components/_side-nav.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_split-buttons.scss", "app/stylesheets/foundation/components/_split-buttons.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_sub-nav.scss", "app/stylesheets/foundation/components/_sub-nav.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_switch.scss", "app/stylesheets/foundation/components/_switch.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_tables.scss", "app/stylesheets/foundation/components/_tables.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_tabs.scss", "app/stylesheets/foundation/components/_tabs.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_thumbs.scss", "app/stylesheets/foundation/components/_thumbs.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_tooltips.scss", "app/stylesheets/foundation/components/_tooltips.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_top-bar.scss", "app/stylesheets/foundation/components/_top-bar.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_type.scss", "app/stylesheets/foundation/components/_visibility.scss"
get "https://raw.github.com/felipecabargas/camorra/master/assets/scss/foundation/components/_visibility.scss", "app/stylesheets/foundation/components/_type.scss"


# JS
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation.js", "public/javascripts/foundation.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation.min.js", "public/javascripts/foundation.min.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/vendor/fastclick.js", "public/javascripts/vendor/fastclick.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/vendor/jquery.cookie.js", "public/javascripts/vendor/jquery.cookie.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/vendor/jquery.js", "public/javascripts/vendor/jquery.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/vendor/modernizr.js", "public/javascripts/vendor/modernizr.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/vendor/placeholder.js", "public/javascripts/vendor/placeholder.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.abide.js", "public/javascripts/foundation/foundation.abide.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.accordion.js", "public/javascripts/foundation/foundation.accordion.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.alert.js", "public/javascripts/foundation/foundation.alert.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.clearing.js", "public/javascripts/foundation/foundation.clearing.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.dropdown.js", "public/javascripts/foundation/foundation.dropdown.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.equalizer.js", "public/javascripts/foundation/foundation.equalizer.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.interchange.js", "public/javascripts/foundation/foundation.interchange.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.joyride.js", "public/javascripts/foundation/foundation.joyride.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.js", "public/javascripts/foundation/foundation.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.magellan.js", "public/javascripts/foundation/foundation.magellan.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.offcanvas.js", "public/javascripts/foundation/foundation.offcanvas.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.orbit.js", "public/javascripts/foundation/foundation.orbit.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.reveal.js", "public/javascripts/foundation/foundation.tooltip.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.tab.js", "public/javascripts/foundation/foundation.reveal.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.tooltip.js", "public/javascripts/foundation/foundation.tab.js"
get "https://raw.github.com/felipecabargas/camorra/master/assets/js/foundation/foundation.topbar.js", "public/javascripts/foundation/foundation.topbar.js"

inject_into_file destination_root('app/stylesheets/application.scss'), "// Load normalize.scss as recommended by Zurb Foundation\n
@import 'normalize';\n\n// Customize certain layout settings in foundation/_settings.scss\n@import 'foundation/settings';\n\n// Use Zurb Foundation\n@import 'foundation';\n", :after => "// @include blueprint\n"

say "Hooray! Camorra is installed."
say "Now you should add Foundation JS to your layout (code below works on both SLIM and HAML):"
say " "
say "=javascript_include_tag 'foundation/foundation.js'"
say "javascript:"
say "  $(document).foundation();%"